### ISSUE TITLE
人的リソース問題

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#1]
### 概要

- 人的なリソースの把握、調整などをここで管理したい。

### Todo

- 仕組み作り
  - [x] メンバーの構成とそれぞれできること、どのポジション希望かをまとめる
  - [ ] 今誰がどの作業をやっていてが可視化できるようにする
  - [ ] それぞれが今何をやらなきゃいけないかを明確にする（ここがゴール）

**Comment by suguru-toyohara** [comment]
### メンバーざっくりまとめ

- 上流：PM/要件定義ポジション
  - @suguru-toyohara 
  - キツネさん
- 下流：開発メンバー
  - キツネさん以外の全員が参加？
  - （異論があれば受け付けます）
- 取りまとめ・意思決定責任者
  - @suguru-toyohara

**Comment by suguru-toyohara** [comment]
### 技術スタック

- pythonできる人が多い印象
- フロントはnext/reactなどがほとんど
- インフラできるのは mochihisaさんと私くらい？キツネさん土佐犬さんは不明

**Comment by ibnr2hc** [comment]
@suguru-toyohara 
> インフラできるのは mochihisaさんと私くらい？キツネさん土佐犬さんは不明

AWS周りであればある程度であればインフラ設計/構築の実務経験あります！😄

**Comment by suguru-toyohara** [comment]
### 引き継ぎHOW/ルール整備

- 基本方針として私が全てを把握しておく
- 自分が忘れることのリスクヘッジも含め、ドキュメントはissueベースで進捗を残しておくこと
  - 実際に次に取り掛かるぜ！って人のために、席を離れる際は何かしら進捗ってことでissuesにメモして離れた方がbetter
  - 自分でも忘れるので
- 全員が全員、全部のことを追う必要は絶対ない。都度聞くオペで良いかと。
  - @suguru-toyohara は全部のことを把握する勢いで目を通しておきます。

**Comment by suguru-toyohara** [comment]
### 誰がなんの作業やってるか可視化

- issuesのAsigneesで登録していくスタイルにしたい。
- そのためにissuesを結構分解するのが必要そう。

**Comment by suguru-toyohara** [comment]
これに関してはmiroをみろって感じでOKになりました。
終了します。
