### ISSUE TITLE
discord関連の開発

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#22]
### 概要

コミュニティの要となるdiscordについて
Webhookなど、Github+Discordについて何かしら設定を行う。

### Todo

- [x] 何が必要かを検証する
- [x] 鯖を引っ越すことも考え、どうするか決める
- [ ] botを導入する

**Comment by Kokohachi** [comment]
個人的タスク

- [ ] Discord のフォーラムとGithubのissueの連携
- [ ] フォーラム?⇄Project
- [ ] PR自動通知、Discord経由レビュー
- [ ] DiscordとGithubのアカウント連携

**Comment by Kokohachi** [comment]
鯖を引っ越す必要はない気がする。カテゴリで事足りる

**Comment by Kokohachi** [comment]
仮のWebhook設置

**Comment by suguru-toyohara** [comment]
最初は凝ったことはせずこんな感じで良いです。

**Comment by suguru-toyohara** [comment]
初期スコープとして出来ているのでclose. 
#50 にて、拡張スコープのissuesを建てたのでそこに引き継ぐ。
