### ISSUE TITLE
レビュー体制構築

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#23]
#22 に関連

### 概要

- コミュニケーションツールとGithubの融合を行い、すぐに連絡がいくように連携
- issuesとレビュー体制についてどうするかを考える必要がある。

### Todo

- [x] レビュー体制をGithubと組み合わせた時にどうするのが最適かを議論する
- [x] ~実装を行う~ → #22 に統合

**Comment by Kokohachi** [comment]
Discordの活用があるなら、Botタスクと連携したほうが良さそう。

**Comment by Shogo-Furuyama** [comment]
(discord鯖の設定権限さえあれば)
pull request用のwebhook作成するのはどうでしょうか(多分既出)
以下資料
https://docs.github.com/ja/webhooks/about-webhooks

**Comment by suguru-toyohara** [comment]
みなさま意見ありがとうございます。
基本的にGithub+Webhookで対応しようと思います。

なので、 #22 にこのissuesは統合します。
