### ISSUE TITLE
コードリファクタリング vol.1

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#25]
### 概要

- 現状コンポーネント内に異常なほど詰まったコードが展開されているため、これを切り出したい。
- map/1と言うルーティングは不要なので、それを改善する

### Todo

- [x] コンポーネントの切り出し
  - [x] Mapコンポーネントの作成
  - [x] Map内のポインタを表示するためのコンポーネントの作成
  - [x] Map内のポインタ詳細を表示するためのコンポーネントを作成
- [x] ルーティングの整理

**Comment by minagishl** [comment]
- 避難所一覧をコンポーネントに変更しました
- マップのポインタをコンポーネントに変更しました
- マップに表示されているポインタをホバーすることにより詳細を表示するコンポーネントを追加しました
- 不要なルーティングを削除しました

プルリクエスト
https://github.com/suguru-toyohara/mapprint-shelter-simeji/pull/2

**Comment by suguru-toyohara** [comment]
承知！みます

**Comment by suguru-toyohara** [comment]
今日中に私の方で引き継ぎます。

**Comment by suguru-toyohara** [comment]
PRマージしましたので、Closeといたします。
