### ISSUE TITLE
地図ポイントの詳細情報を表示する機能

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#27]
### Todo

- [ ] 地図ポイント自体を変更できるようにしたい
- [x] フォーカス時tooltipで表示できるようにしたい
- [x] カラム表示でも詳細情報を表示したい。
- [x] geoJsonに関してダミーデータを入れ込む（元のサーバに負荷入りっぱなしっぽいので避ける）

**Comment by suguru-toyohara** [comment]
### 地図ポイント自体を変更できるようにしたい

これはちょっと言葉足らずで申し訳ないんですが、要求は以下の通りです

- 地図のカラム表示時Iconをavatar attributeにIconコンポーネントを仕込むとそれに変化する
- 地図上のポインタそのもののIconをchildrenやicon attribute等で拾って表示するように書けるようにしてほしい

**Comment by suguru-toyohara** [comment]
Task 2については↑のPRで実現済み

**Comment by suguru-toyohara** [comment]
# geoJsonに関してダミーデータを入れ込むの詳細

- 現在JSONで取ってきてるデータについて毎回鯖に問い合わせてるっぽいので、.tsファイルでも良いのでobjectで書き込んどく

**Comment by minagishl** [comment]
カラム表示の際に詳細を表示する機能は完成しました

**Comment by suguru-toyohara** [comment]
Mergeしたので、Closeといたします。
引越しのため、中途半端になってますが、やり残したことはPRに書いておきました。
よろしくお願い致します。
