### ISSUE TITLE
各種類似OSSの現在の状況を調査したい

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#29]
### 概要

- 使えるものは使いたいと言う意図がある
- 私たちの出せるバリューと言うのも考えねばならないので、類似OSS調査は必要

### todo

- [x] 類似OSSの現在を調べる。

**Comment by suguru-toyohara** [comment]
### やり方

- このチケットにバシバシ情報を書いて行ってください。
- 調べる対象は基本はMap系OSSで良いです。
- ただし、能登半島自身に関するものであれば、Map関係なくともここに書いて行ってください。

**Comment by lumiere41** [comment]
**類似OSS**
----------

ソーシャルオープンプラットフォーム利用推進フォーラム(SOPPF)
https://www.soppf.org/
[国立研究開発法人 防災科学技術研究所](http://www.bosai.go.jp/)が、地域防災向けプラットフォームとして「[eコミュニティ・プラットフォーム](https://ecom-plat.jp/)」を開発。
開発したソフト「eコミウエア」を[GPL（GNU一般利用許諾契約書](https://www.gnu.org/licenses/)に基づき、オープンソースソフトウエア（OSS)として商用利用を含め無償提供しています。

＜「[eコミュニティ・プラットフォーム](https://ecom-plat.jp/)（略称「ｅコミ」）のソフト群＞

[eコミグループウェア](https://ecom-plat.jp/index.php?gid=10454)
[eコミマップ](https://ecom-plat.jp/index.php?gid=10457)　（ [庁内情報共有・発信基盤システム](http://ecom-plat.jp/group.php?gid=10671)）
[相互運用gサーバー　](https://ecom-plat.jp/group.php?gid=10459)（ [センサー情報相互運用配信システム](http://ecom-plat.jp/group.php?gid=10664)）
[災害リスク情報クリアリングハウス](https://ecom-plat.jp/group.php?gid=10620)
[見守り情報管理システム](https://ecom-plat.jp/group.php?gid=10610)
[災害ボランティアセンター運営支援キット（災害VCキット）](https://ecom-plat.jp/index.php?gid=10679)
[災害アーカイブシステム](https://ecom-plat.jp/group.php?gid=10637)

「ｅコミュニティ・プラットフォーム」は国立研究開発法人防災科学技術研究所の登録商標です。
※運営する団体が、2019年4月1日から縮小▶ボランティア活動化とニュースに記載あり

eコミウエア｜ダウンロード：
https://www.soppf.org/index.php?gid=10008

----------

OpenStreetMap
https://www.openstreetmap.org/#map=5/35.568/134.385
OpenStreetMap は数千ものウェブサイト、モバイル アプリ、ハードウェア機器に地図データを提供しています。

[about]
https://www.openstreetmap.org/about

[関連]
オープンソース地理情報システムを用いた地域防災マップ作成支援システムの開発と実践
https://www.jstage.jst.go.jp/article/jscejsp/74/2/74_I_19/_pdf

オープンソースマップが震災のネパールの救助作戦を支えた[Wired.jpニュース]
https://wired.jp/2015/06/02/open-source-maps-rescues-in-nepal/

----------
### R6能登半島地震特化

石川/富山県で営業中の銭湯や給水所を確認できるサイトを被災者支援としてOSSで公開しました
zenn記事：
https://zenn.dev/t0m0120/articles/4801ab486c337c

github:
https://github.com/t0m0120/IshikawaTakidashiMap

営業している銭湯マップ:
https://ishikawatakidashimap.pages.dev/Sentou

給水情報マップ:
https://ishikawatakidashimap.pages.dev/Water

支援物資拠点：
https://ishikawatakidashimap.pages.dev/Supplies

営業している医療機関マップ：
https://ishikawatakidashimap.pages.dev/Hospital

----------

**Comment by lumiere41** [comment]
OSSを活用した「八王子市防災マップ」
https://www.city.hachioji.tokyo.jp/emergency/bousai/m12873/001/p031341.html

github：
https://github.com/sankichi92/shikuchoson-hazardmap-template

- URLをクリックすると、住所の入力などは不要で、八王子市全体のマップが表示されます。
- チェックを入れる機能により、知りたいハザード情報などの表示が選択できます。
- 表示される地図の拡大、縮小、地図の移動ができます。
- ※市の調査情報は含まれない、オンライン環境でのみ使用可

スマホからの閲覧について[[PDF](https://www.city.hachioji.tokyo.jp/emergency/bousai/m12873/001/p031341_d/fil/smartphone.pdf)]

**Comment by suguru-toyohara** [comment]
ありがとうございます！めちゃめちゃ助かりました！

**Comment by suguru-toyohara** [comment]
## code for japan project noto

- 能登半島地震で、必要な支援情報をQA方式でユーザが集められるOSSサイト
- https://civictechsodegaura.org/__NOTO__/

**Comment by suguru-toyohara** [comment]
### まとめ

- 一旦必要な情報はここまででOSSで取れる可能性は出てきた。
- 私たちができることの一つに 災害支援情報のGithubへのアップロードがあるかもしれない
  - それだけで救える命、支えるプロダクトがあるかもしれないとも気づけた。
- また、同様にSNS視点でのOSSは存在しないこともわかった。
- ↑愚直に新規性を求めても良くないのだが、できることなら流用したいというお気持ちがあったので。
