### ISSUE TITLE
要求・要件をまとめる

### ISSUE THREAD

**Issue by suguru-toyohara** [tech-creative-club/disaster-platform#3]
### 概要

- 要求や要件をまとめる
- 以前に作成したものを形にする作業

### 1/3 3時時点でコンセンサスを取れてる要件

- 個の情報より多数の情報を集約し、公表するWebサービスを立ち上げる
- より具体的に言えば、避難所IDに対して何が足りない、通電しているしていない、断水しているしていないなどを集めて見える化
- 公的なもの以外にユーザが勝手に避難所として場所データを作っていい。

### 疑問点・議論の余地があるポイント

- 避難所で情報を取りまとめるのであれば、それは自治体の仕事では？
  - 自治体では無理だけどニーズを汲み取れない部分を拾いきれたら嬉しいけども、、、
- 概念がわかり辛い(以前の方がシンプルでは？)

# 以下は昔の情報
### 文字ベースで決めてた要件

考えないこと：
- 基本ユーザ側がテキストをPushするといったことは考えない。
  - 画像等、exifなどで検証可能なデータであればユーザコンテンツをPushしてもOKとしたい。
  - それ以外の文字ベースでの入力は不可としたい。
- 情報の真偽については問わない
  - というのも、個で発生した外れ値などのデータは無視すること＋情報の多さで情報の正確さは上がるから。
- 一旦フロントはWebベースでしか考えない。
  - MVPスタイルで作りたいので。フロントは実績がついてきたら有志がいくらでも様々な媒体で開発できる。
- Twitterみたいな掲示板のようなことはやらない。

やりたきこと：

- 以下の統計情報を位置情報含め取得し、精査した上で公表したい。
  - 停電
  - 断水
  - 浸水
  - 物資提供
  - 物資不足
  - みなどこに避難しているか
    - みんな避難してますよ！という情報は、避難を促す点でかなり有用
  - ボランティア過不足・必要不要
  - etc...（何をするかはコンセンサスを取りたい）
- その理由
  - 統計は嘘をつかない（だろう）
  - LINEとの連携も可能。
  - アーキテクチャも簡単
  - セキュア

**Comment by suguru-toyohara** [comment]
### 他にもあった意見

- ガソリンの給油場所みたいに、結構ジャンルが広くて追いきれないのでは？
- 必要な情報は結構無限にある気がする。
  - そういう意味で固定で良いのか？というのは議論の余地がある。

**Comment by suguru-toyohara** [comment]
### 今後の作業Todo

- [ ] 要求・要件をまとめた図・ポンチ絵を作る
- [ ] コンセンサスを取る。（ビジョンは明確になってきたので、何をすべきかがはっきりとわかる状態に持っていく）
- [ ] 考慮漏れ等がないかを確認する（といっても、キリがないのでほどほどに）

**Comment by suguru-toyohara** [comment]
### ボイチャ議題

#### 考慮漏れについて考えたい。

**Comment by suguru-toyohara** [comment]
https://miro.com/app/board/uXjVN9ifFnE=/
ここでメインボードを作成中

**Comment by suguru-toyohara** [comment]
### 第1陣のスコープで考えなくて良いこと

- 台風・豪雨・洪水の件（地震と性質が異なるため）
- 119番自動通報などのシステム構築

**Comment by suguru-toyohara** [comment]
### 2024/1/3 1:00

- 避難所というものを要として、情報を集約するという方が良いかも。
- 結局解決したい問題っていうのが、情報の集約というのであれば、個の情報は必要ないわけで、GPSで統計をとるのはBadかも
- なので、避難所という単位で情報を集約してしまえば良いということになる。

**Comment by suguru-toyohara** [comment]
### 疑問

- 避難所IDってのはどうやって振るのか？
- まずどうやって広める？
- 最初にGPSって言い始めたのは、そういう泥臭い避難所IDの紐付けが必要ないからっていう話もあったけど...

### 広められるストーリー

- 避難所にいる人で現状を変えたい人にリーチできれば広まるはず。
- 現状を変えたいと思ってる人は被災者であって自治体ではない。

### 避難所逆引き

- スクレイピングもできるが、どうだろう
- ↑国土地理院にCSVがある。

### 自分たちの出したいバリューとは

- 一次避難に対しての物資不足・状況の共有によって対策の速度を上げる
- 避難所にきた被災者が、欲しかったものがない場合に、別の10分先の避難所で見つけられる可能性を広げることはできる
  - 移動するのは戻るに含まれて禁止されそうなイメージはある。あと避難所単位で生存確認とかしている場合もあるかも。
  - なので、安易に移動されると自治体からやめてほしいと言われることもありそう。
  - 被災した人に聞く必要はあるかも。

**Comment by nakaji-kazu** [comment]
### 本アプリの利用者
 - 管理者：避難所のまとめ役の方？
 - 被災者：避難所に逃げてきた、スマホを持っている人

### 想定される機能
 - 災害用アンケート作成機能
 - アンケート結果の集計/特定連絡先への発信機能
 - 被災地IDごとにアプリ内での発信およびTwitterなどのSNS連携による発信機能

### バリューをもっとも発揮する想定の範囲
 - 被災者が避難完了後の各避難所で生活を安定させるまで

**Comment by suguru-toyohara** [comment]
### バックエンド

- インフラを作らねばならない(LINEはめっちゃ高い)

**Comment by suguru-toyohara** [comment]
### そういえばの話

- NERVみたいな発信アカウント運営作っても良い気はしている。

**Comment by suguru-toyohara** [comment]
### メモ

これは全然後の話だけど

- 災害救助アカウント/災害物資運びアカウントが常時位置情報を流し、今どこにきているのかというのを把握できるシステムも良い気がしている

**Comment by suguru-toyohara** [comment]
あとはドキュメント班に任せるのと
これ以上深ぼっても時間の無駄なので認識を合わせられたので
一旦このissuesは終了にします！ありがとうございました。
